### ISSUE TITLE
Finne komponenter

### ISSUE THREAD

**Issue by magaust** [IT2810/it2810-webutvikling-h18-prosjekt-3-34#2]
Knapper: Pluss/legg til
Labels
Input-felt

**Comment by ErikSteLarsen** [comment]
Har funnet en komponent for "pedometer", altså skrittelleren som fungerte ganske bra!
Vi kan gjøre noen endringer i denne komponenten for å få ut ulik informasjon fra skrittelleren i enheten. Per nå får man ut antall skritt i "currentSession" og antall skritt de siste 24 timene.

**Comment by ErikSteLarsen** [comment]
Vi bruker ikke så veldig mange ferdiglagde komponenter, men lager heller våre egne ganske fra bunnen av. Det hadde kanskje vært en fordel å finne noen ferdiglagde, men vi har ikke trengt så mange alt for kompliserte komponenter enda.
