### ISSUE TITLE
Implementere poengsystem.

### ISSUE THREAD

**Issue by magaust** [IT2810/it2810-webutvikling-h18-prosjekt-3-34#6]
Gi poeng for oppfylt mål.
Vise totalscore = lagre alle poeng.

**Comment by ErikSteLarsen** [comment]
Viser nå antall mål som er oppfylt for i går, i dag og i morgen. 
Teller opp disse og viser en tekst med "antall todos fullført".

**Comment by ErikSteLarsen** [comment]
Denne issuen er vel egentlig ferdig da?
