### ISSUE TITLE
Lage gjøremål komponent

### ISSUE THREAD

**Issue by magaust** [IT2810/it2810-webutvikling-h18-prosjekt-3-34#9]
Tekst som beskriver målet og en "V" gjennomført knapp og "X" slette knapp

**Comment by ErikSteLarsen** [comment]
Dette ble egentlig gjennomført i listview commiten, der jeg hadde jobbet på både listview og komponentene i listviewet. Foreløpig er dette bra nok her, og closer derfor denne issuen.
